### ISSUE TITLE
Any demo or tutorials?

### ISSUE THREAD

**Issue by com3dian** [Prabh1804/Mind_Mapper.github.io#1]
Hi, 
I wonder there is any live demos I can view? I tried `http://mind_mapper.github.io/` but it is 404, thanks.

**Comment by Prabh1804** [comment]
Ok because you search incorrect link you should go to my portfolio https://Prabh1804.github.io or use the link https://Prabh1804.github.io/Mind_Mapper.github.io Sent from my Galaxy
-------- Original message --------From: com3dian ***@***.***> Date: 21/04/2024  3:01 am  (GMT+05:30) To: "Prabh1804/Mind_Mapper.github.io" ***@***.***> Cc: Subscribed ***@***.***> Subject: [Prabh1804/Mind_Mapper.github.io] Any demo or tutorials? (Issue #1) 
Hi,
I wonder there is any live demos I can view? I tried http://mind_mapper.github.io/ but it is 404, thanks.
